services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    develop:
      watch:
        - path: pyproject.toml
          action: rebuild
        - path: uv.lock
          action: rebuild
        - path: Dockerfile
          action: rebuild

        - path: .
          target: /app
          action: sync
          ignore:
            - __pycache__/
            - .git
            - .venv

  redis:
    image: redis:alpine

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
