import sqlmodel

"""empty message

Revision ID: 127386615fa5
Revises: de67ff32df3b
Create Date: 2026-06-11 09:28:53.034019

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "127386615fa5"
down_revision: Union[str, Sequence[str], None] = "de67ff32df3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deadletterqueue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("err_msg", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("replayed_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscription.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deadletterqueue_attempt_no"),
        "deadletterqueue",
        ["attempt_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deadletterqueue_err_msg"), "deadletterqueue", ["err_msg"], unique=False
    )
    op.create_index(
        op.f("ix_deadletterqueue_event_id"),
        "deadletterqueue",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deadletterqueue_payload"), "deadletterqueue", ["payload"], unique=False
    )
    op.create_index(
        op.f("ix_deadletterqueue_subscription_id"),
        "deadletterqueue",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deadletterqueue_tenant_id"),
        "deadletterqueue",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deadletterqueue_tenant_id"), table_name="deadletterqueue")
    op.drop_index(
        op.f("ix_deadletterqueue_subscription_id"), table_name="deadletterqueue"
    )
    op.drop_index(op.f("ix_deadletterqueue_payload"), table_name="deadletterqueue")
    op.drop_index(op.f("ix_deadletterqueue_event_id"), table_name="deadletterqueue")
    op.drop_index(op.f("ix_deadletterqueue_err_msg"), table_name="deadletterqueue")
    op.drop_index(op.f("ix_deadletterqueue_attempt_no"), table_name="deadletterqueue")
    op.drop_table("deadletterqueue")
    # ### end Alembic commands ###
