import sqlmodel

"""empty message

Revision ID: a26f4b9f89af
Revises: 
Create Date: 2026-06-11 22:03:20.167009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26f4b9f89af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_api_key_hash'), 'tenant', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=True)
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'event_type', 'target_url', name='unique_tenant_event_url')
    )
    op.create_index(op.f('ix_subscription_tenant_id'), 'subscription', ['tenant_id'], unique=False)
    op.create_table('deadletterqueue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('err_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('replayed_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadletterqueue_attempt_no'), 'deadletterqueue', ['attempt_no'], unique=False)
    op.create_index(op.f('ix_deadletterqueue_err_msg'), 'deadletterqueue', ['err_msg'], unique=False)
    op.create_index(op.f('ix_deadletterqueue_event_id'), 'deadletterqueue', ['event_id'], unique=False)
    op.create_index(op.f('ix_deadletterqueue_payload'), 'deadletterqueue', ['payload'], unique=False)
    op.create_index(op.f('ix_deadletterqueue_subscription_id'), 'deadletterqueue', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_deadletterqueue_tenant_id'), 'deadletterqueue', ['tenant_id'], unique=False)
    op.create_table('deliverylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('err_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverylog_event_id'), 'deliverylog', ['event_id'], unique=False)
    op.create_index(op.f('ix_deliverylog_subscription_id'), 'deliverylog', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_deliverylog_tenant_id'), 'deliverylog', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliverylog_tenant_id'), table_name='deliverylog')
    op.drop_index(op.f('ix_deliverylog_subscription_id'), table_name='deliverylog')
    op.drop_index(op.f('ix_deliverylog_event_id'), table_name='deliverylog')
    op.drop_table('deliverylog')
    op.drop_index(op.f('ix_deadletterqueue_tenant_id'), table_name='deadletterqueue')
    op.drop_index(op.f('ix_deadletterqueue_subscription_id'), table_name='deadletterqueue')
    op.drop_index(op.f('ix_deadletterqueue_payload'), table_name='deadletterqueue')
    op.drop_index(op.f('ix_deadletterqueue_event_id'), table_name='deadletterqueue')
    op.drop_index(op.f('ix_deadletterqueue_err_msg'), table_name='deadletterqueue')
    op.drop_index(op.f('ix_deadletterqueue_attempt_no'), table_name='deadletterqueue')
    op.drop_table('deadletterqueue')
    op.drop_index(op.f('ix_subscription_tenant_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.drop_index(op.f('ix_tenant_api_key_hash'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
