import sqlmodel

"""empty message

Revision ID: 316b8cd1235f
Revises: b6cd8c0705ca
Create Date: 2026-06-11 07:52:42.152385

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '316b8cd1235f'
down_revision: Union[str, Sequence[str], None] = 'b6cd8c0705ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
