import sqlmodel

"""empty message

Revision ID: b6cd8c0705ca
Revises: 8163896740e9
Create Date: 2026-06-10 20:28:22.965450

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6cd8c0705ca"
down_revision: Union[str, Sequence[str], None] = "8163896740e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deliverylog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("err_msg", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscription.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deliverylog_event_id"), "deliverylog", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_deliverylog_subscription_id"),
        "deliverylog",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_deliverylog_tenant_id"), "deliverylog", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deliverylog_tenant_id"), table_name="deliverylog")
    op.drop_index(op.f("ix_deliverylog_subscription_id"), table_name="deliverylog")
    op.drop_index(op.f("ix_deliverylog_event_id"), table_name="deliverylog")
    op.drop_table("deliverylog")
    # ### end Alembic commands ###
