import sqlmodel

"""empty message

Revision ID: de67ff32df3b
Revises: 316b8cd1235f
Create Date: 2026-06-11 09:25:51.675854

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de67ff32df3b"
down_revision: Union[str, Sequence[str], None] = "316b8cd1235f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_tenant_event_url",
        "subscription",
        ["tenant_id", "event_type", "target_url"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_tenant_event_url", "subscription", type_="unique")
    # ### end Alembic commands ###
